default:
  database:
    neo4j:
      uri: bolt://localhost:7687
      user: neo4j
      password: 12345678a
  fhir:
    uri: https://healthcare.cwbyminsait.com/ehrserver/fhir

local:
  service:
    host: 127.0.0.1
    port: 5000
