default:
  database:
    neo4j:
      uri: bolt://localhost:7687
      user: neo4j
      password: 12345678a
      index_name: fhir_text_large
      fulltext_index_name: node_text_index
      embedder_model: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
  fhir:
    uri: https://healthcare.cwbyminsait.com/ehrserver/fhir
  dsforms:
    uri: https://healthcare.cwbyminsait.com/dsforms/fhir/rest

local_ngm:
  service:
    host: 127.0.0.1
    port: 5000

local_moa:
  service:
    host: 127.0.0.1
    port: 5000

develop:
  service:
    host: https://healthcare.cwbyminsait.com
    port: 8080